name: First Workflow
on: workflow_dispatch 
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "hello world one"
          echo "Hello world two"
      - name: print goodbyee 
        run: echo "Done Byee!" 
